### ISSUE TITLE
Support mounting yaml and json files as is?

### ISSUE THREAD

**Issue by ljani** [Mic92/sops-nix#120]
My current use case: I'd like to pass a `sops` encrypted `.yaml` configuration file to my app after decryption as is instead of picking a single key from the file. So, `sops-nix` is a little too clever for my use case and it should focus only on decrypting the file, not parsing it.

In other words, I have this file `./secrets/my-config.yaml` in my flake:

```yaml
my-secret1: ENC[AES256_GCM,data:tkyQPQODC3g=,iv:yHliT2FJ74EtnLIeeQtGbOoqVZnF0q5HiXYMJxYx6HE=,tag:EW5LV4kG4lcENaN2HIFiow==,type:str]
my-secret2: ENC[AES256_GCM,data:tkyQPQODC3g=,iv:yHliT2FJ74EtnLIeeQtGbOoqVZnF0q5HiXYMJxYx6HE=,tag:EW5LV4kG4lcENaN2HIFiow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
...
```

It should be mounted as `/run/secrets/my-config.yaml`:

```yaml
my-secret1: hello
my-secret2: hello
```

Then I could pass the `/run/secrets/my-config.yaml` to my app to read any secrets from.

I could do this using a `format=binary` file, but then I'd lose eg. syntax highlight based on the file extension and have to pass use `format=binary` everywhere. Alternatively, I could use a literal multi line yaml string, but then again I'd lose highlight.

I wonder if this is already supported, because the `README.md` [mentions `home-assistant-secrets.yaml`](https://github.com/Mic92/sops-nix/blob/ae84c313c5250a832d61dae9e1e659b27542c47b/README.md#L558), which is similar to what I'm looking for? But I think that was defined as something like this:

```yaml
home-assistant-secrets.yaml: |
    my-secret1: hello
    my-secret2: hello
```

(Notice how the renderer fails to highlight the yaml keys `my-secret1` and `my-secret2`).

Does this make any sense to you?
