### ISSUE TITLE
Is there a technical reason why yaml aliases are expanded at encryption time?

### ISSUE THREAD

**Issue by stratosgear** [Mic92/sops-nix#480]
I am weird and I have a usecase where I would like to use a secrets yaml like:

```
passphrases:
    pass1: &pass1 simplePass1
    pass2: &pass2 differentPass
restic:
    passhprases:
        backupDocs:  *pass1
        backupsRepos: *pass2
        backupMusic: *pass1
...
```

This is a simplified example.

It seems that immediately after I `sops secrets/vault.yaml` and enter the above file, sops seems to expand all aliases and save that file.

If I immediately reopen the file, again with a  `sops secrets/vault.yaml` I see that I have lost all my & and * aliases.

In the simplified example above it might not be a huge problem, but for heavier usage there is a ton of unnecessary duplication that I am required to maintain. :(

Would there be a way to do the final expansion at deployment time...?

Hopefully this makes sense!

Thanks for a wonderful tool, in any case! :)
