### ISSUE TITLE
encrypted yaml with lists sops nixos

### ISSUE THREAD

**Issue by segator** [Mic92/sops-nix#481]
in case my encrypted yaml have a list in the format of 

 ```yaml
wireless:
    nmconnections:
        - name: Wifi1
          content: |
            [connection]
            ....
        - name: Wifi2
          content: |
            [connection]
            ....
```

how I can iterate this so  the nmconnection secret of each wifi is stored at /etc/NetworkManager/system-connections/$name

not clear to me how to achieve this, maybe is there another way to achieve same thing? encrypted wifi configuration, (is not enough with the PSK), the company I work also requires more configuration that is why I considering pass the whole nmconnection file
